
project_id = "fxbgfoymkdtmnlnuqqty"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[edge_functions]
enabled = true
port = 54323

[functions.request-app-reset]
verify_jwt = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15
