// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxbgfoymkdtmnlnuqqty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4Ymdmb3lta2R0bW5sbnVxcXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzg4MDYsImV4cCI6MjA2MDIxNDgwNn0.8timNyreYUzWaSyc4bQcn8bH8xZqatCdNGnLeqKPVGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);